import sys
from setuptools import setup, find_packages

# Common dependencies
common_dependencies = [
    "pymongo",
    "SQLAlchemy",
    "sqlalchemy-utils",
    "alembic",
    "psycopg2-binary",
    "repository-sqlalchemy",
    "repository-mongodb",
    "pytest-playwright",
    "beautifulsoup4>=4.12.2",
    "colorama==0.4.6",
    "distro==1.8.0",
    "openai",
    "playsound==1.2.2",
    "pyyaml==6.0",
    "readability-lxml==0.8.1",
    "requests",
    "tiktoken==0.3.3",
    "gTTS==2.3.1",
    "docker",
    "google-api-python-client",
    "redis",
    "weaviate-client",
    "sentence-transformers",
    "orjson",
    "Pillow",
    "jsonschema",
    "click",
    "grpcio",
    "grpcio-tools", 
    "toml",
    "python-dotenv",
    "uvicorn",
    "fastapi",
    "strawberry-graphql",
]

setup(
    name="autobyteus",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=common_dependencies,
    extras_require={
        "dev": [
            "coverage",
            "flake8",
            "numpy",
            "pre-commit",
            "black",
            "isort",
            "gitpython==3.1.31",
            "auto-gpt-plugin-template",
            "mkdocs",
            "pytest",
            "asynctest",
            "pytest-asyncio",
            "pytest-benchmark",
            "pytest-cov",
            "pytest-integration",
            "pytest-mock",
            "vcrpy",
            "pytest-vcr",
            "llm_chatui_provider @ git+https://github.com/AFE-AI/llm_chatui_provider.git@main",
        ],
    },
    python_requires=">=3.8",
    author="Ryan Zheng",
    author_email="ryan.zheng.work@example.com",
    description="A library for automating software development tasks",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/your-username/autobyteus",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    package_data={
        "autobyteus": ["py.typed"],
    },
)