version: '3.8'

services:
  milvus:
    container_name: milvus
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - ETCD_USE_EMBED=true
    restart: unless-stopped

volumes:
  milvus_data: