[llm_integration]
type = "puppeteer"

[browser]
url = "your_browser_url"

[domain]
value = "your_domain"

[selectors]
textarea_selector = "textarea[placeholder=\"Send a message...\"]"
copy_button_selector = "div.flex.flex-col.items-center > div:nth"

[workflows]
enabled_workflows = ["automated_coding_workflow"]

